changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - "enhancement"

    - title: "🐛 Bug Fixes"
      labels:
        - "bug"

    - title: "📚 Documentation"
      labels:
        - "documentation"

    - title: "⚡ Performance"
      labels:
        - "type:performance"

    - title: "🔒 Security"
      labels:
        - "type:security"

    - title: "🧪 Tests"
      labels:
        - "type:tests"

    - title: "♻️ Refactoring"
      labels:
        - "type:refactor"

  exclude:
    labels:
      - "status:needs-info"
      - "status:blocked"
